// Generated by https://quicktype.io

export interface EventsData {
  ok: boolean;
  records: number;
  events: Event[];
}

export interface Event {

  //Id de evento
  _id: string

  //Nombre del evento
  name: string,

  //Descripcion o sinopsis
  description: string,

  //Imagen / poster del evento
  image: string,

  //Slug en formato nombre-de-evento
  slug: string

  //Imagenes adicionales del evento
  images: string[],

  //Videos adicionales del evento
  videos: string[],

  //Precio de zona A
  sectionAPrice: number,

  //Precio de zona B
  sectionBPrice: number,

  //Tipo de evento 
  type: 'Numerado' | 'No Numerado',

  //Si el evento esta disponible o no
  active: boolean

  //Indica el numero de funciones disponibles para el evento
  totalFunctions: number
}