// Generated by https://quicktype.io

export interface SectionsData {
  ok:       boolean;
  sections: Section[];
}

export interface Section {
  _id:       string;
  eventId:   EventID;
  name:      string;
  price:     number;
  order:     number;
  createdAt: string;
  updatedAt: string;
  __v:       number;
}

export interface EventID {
  _id:             string;
  hour:            string;
  day:             string;
  coach:           string;
  stage:           Stage;
  className:       string;
  totalSpaces:     number;
  availableSpaces: number;
  soldOutSpaces:   number;
  createdAt:       string;
  updatedAt:       string;
  __v:             number;
}

export interface Stage {
  label: string;
  value: string;
  _id:   string;
}
