// Generated by https://quicktype.io

export interface TicketsData {
  ok:      boolean;
  tickets: Ticket[];
}

export interface Ticket {
  _id:       string;
  eventId:   EventID;
  sectionId: SectionID;
  number:    number;
  soldOut:   boolean;
  __v:       number;
  createdAt: string;
  updatedAt: string;
}

export interface EventID {
  _id:             ID;
  hour:            Hour;
  day:             string;
  coach:           Coach;
  stage:           Stage;
  className:       ClassName;
  totalSpaces:     number;
  availableSpaces: number;
  soldOutSpaces:   number;
  createdAt:       string;
  updatedAt:       string;
  __v:             number;
}

export enum ID {
  The620E9D0C301D7F564E61A1A9 = "620e9d0c301d7f564e61a1a9",
}

export enum ClassName {
  CoachesTalk = "Coaches Talk",
}

export enum Coach {
  Akiniko = "Akiniko",
}

export enum Hour {
  The1530 = "15:30",
}

export interface Stage {
  label: Label;
  value: Value;
  _id:   StageID;
}

export enum StageID {
  The620E9D0C301D7F564E61A1Aa = "620e9d0c301d7f564e61a1aa",
}

export enum Label {
  DharmaTalks = "Dharma Talks",
}

export enum Value {
  DharmaTalks = "dharma-talks",
}

export interface SectionID {
  _id:       PurpleID;
  eventId:   ID;
  name:      Name;
  price:     number;
  order:     number;
  createdAt: string;
  updatedAt: string;
  __v:       number;
}

export enum PurpleID {
  The620Eb0A2976A5D19D4Ce7243 = "620eb0a2976a5d19d4ce7243",
  The620Fe3729A9B648379551173 = "620fe3729a9b648379551173",
  The620Fe3A99A9B648379551175 = "620fe3a99a9b648379551175",
  The620Fe3B29A9B648379551177 = "620fe3b29a9b648379551177",
}

export enum Name {
  A = "A",
  B = "B",
  C = "C",
  Vip = "VIP",
}
