import Head from 'next/head'
import { FC } from 'react'

interface Props {
    children?: any;
}


export const Layout: FC<Props> = ({ children }) => {



    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            
            <p>This is the Layout</p>
            { children }
        </>
    )

}